test_data = [
    {"text": "I absolutely love this product!", "label": "positive"},
    {"text": "This is the worst experience I've ever had.", "label": "negative"},
    {"text": "I am extremely happy with the service.", "label": "positive"},
    {"text": "I hate this so much.", "label": "negative"},
    {"text": "It's okay, not the best but not the worst either.", "label": "neutral"},
    {"text": "The quality is amazing, I'm very satisfied!", "label": "positive"},
    {"text": "Terrible product, I want a refund.", "label": "negative"},
    {"text": "I'm feeling really good about this.", "label": "positive"},
    {"text": "This is a disaster.", "label": "negative"},
    {"text": "Quite mediocre, nothing special.", "label": "neutral"},
    {"text": "Absolutely fantastic!", "label": "positive"},
    {"text": "I regret buying this, it's awful.", "label": "negative"},
    {"text": "Not bad, could be better.", "label": "neutral"},
    {"text": "I'm thrilled with my purchase!", "label": "positive"},
    {"text": "This is so frustrating.", "label": "negative"},
    {"text": "I'm not sure how I feel about this.", "label": "neutral"},
    {"text": "Best decision ever!", "label": "positive"},
    {"text": "Worst decision ever.", "label": "negative"},
    {"text": "It's fine, nothing extraordinary.", "label": "neutral"},
    {"text": "Super happy with this!", "label": "positive"},
    {"text": "This makes me very angry.", "label": "negative"},
    {"text": "It's average, nothing more.", "label": "neutral"},
    {"text": "Love it, will buy again!", "label": "positive"},
    {"text": "This is unacceptable.", "label": "negative"},
    {"text": "It's okay, I guess.", "label": "neutral"},
    {"text": "I'm over the moon with this product!", "label": "positive"},
    {"text": "Absolutely horrible.", "label": "negative"},
    {"text": "It's not bad at all.", "label": "neutral"},
    {"text": "I couldn't be happier!", "label": "positive"},
    {"text": "This is the worst.", "label": "negative"},
    {"text": "It's pretty decent.", "label": "neutral"},
    {"text": "I'm ecstatic about this!", "label": "positive"},
    {"text": "So disappointing.", "label": "negative"},
    {"text": "It's alright, I suppose.", "label": "neutral"},
    {"text": "I'm so pleased with this.", "label": "positive"},
    {"text": "This is infuriating.", "label": "negative"},
    {"text": "It's fine, nothing amazing.", "label": "neutral"},
    {"text": "Superb, just superb!", "label": "positive"},
    {"text": "I'm really upset about this.", "label": "negative"},
    {"text": "Not great, not terrible.", "label": "neutral"},
    {"text": "Overjoyed with the results!", "label": "positive"},
    {"text": "I hate this product.", "label": "negative"},
    {"text": "It's satisfactory.", "label": "neutral"},
    {"text": "Couldn't be more satisfied!", "label": "positive"},
    {"text": "This product is awful.", "label": "negative"},
    {"text": "It's pretty average.", "label": "neutral"},
    {"text": "I'm in love with this!", "label": "positive"},
    {"text": "This is so bad.", "label": "negative"},
    {"text": "It's okay, just okay.", "label": "neutral"}
]